name: AshesPlugin
version: 0.1
author: AshesKaiser
api-version: 1.16

main: com.AshesKaiser.AshesPlugin.Main
description: AshesKaiser's first plugin

commands:
  shop:
    description: 상점을 엽니다.
    aliases: [상점]

  money:
    description: 플레이어에게 돈을 줍니다.
    aliases: [돈]